### ISSUE TITLE
Aishimai IV

### ISSUE THREAD

**Issue by Cosetto** [TesterTesterov/AI6WINScriptTool#1]
Can you take a look at [this one](https://vndb.org/v14826) script, some of the scripts can't be inserted like sis4_00_prologue.mes and when choosing extract directory it gave error too. I tested on Biniku no Kaori, it works fine for Elf's ai6win I think?
[Aishimai.zip](https://github.com/TesterTesterov/AI6WINScriptTool/files/7788069/Aishimai.zip)

**Comment by TesterTesterov** [comment]
On which Biniku no Kaori did you test (Bangai Hen or Netori Netorare Yari Yarare)?

> it works fine for Elf's ai6win I think
 
 I think it does not quite depend on the studio, since it worked fine with Gakuen Saimin Reido. Just some rare opcode may pop out. Still I need to test it more...

**Comment by Cosetto** [comment]
> On which Biniku no Kaori did you test (Bangai Hen or Netori Netorare Yari Yarare)?
> 
> > it works fine for Elf's ai6win I think
> 
> I think it does not quite depend on the studio, since it worked fine with Gakuen Saimin Reido. Just some rare opcode may pop out. Still I need to test it more...

It's netori netorare one

**Comment by TesterTesterov** [comment]
Okay, I've gotten to the bottom of the issue. Basically, a command popped out. One which have different arguments with Silky Engine's that command. It was not used in other game I have tested, so I did not know about it. It was quite tricky one, actually. It does seems like it has some arguments with offset, but actually it just has 1 argument with byte.

Also I slightly modified string reading system (since AI6WIN's strings in 0x0a command, unlike SilkyEngine's, are not encrypted) and command meanings.

Also has found out what there is a new command which makes a line-breaks in AI6WIN.

Try new release now: [AI6WINScriptTool 1.1](https://github.com/TesterTesterov/AI6WINScriptTool/releases/tag/1.1).

**Comment by Cosetto** [comment]
Thanks. In mean time I tested with [this one](https://vndb.org/v8731), works like charm 
![image](https://user-images.githubusercontent.com/81801486/147653272-eab79256-8b05-4a36-8bed-9f850dc0aff1.png)

**Comment by Cosetto** [comment]
And if possible can you make line breaker string "\n". It's kinda pain to add those line everytime to break line

**Comment by TesterTesterov** [comment]
It would be problematic in my current implementation of disassembler. Basically, to support it, I'd need either make a very bad crutch system or reimplement it all.
Also, it would be misleading, since the engine does not support \n, \t, ]\b or \i special symbols.

Therefore I suggest you another solution. You can just make breaks with \n, but before assembling the script in Notepad++ just replace (extended replacing)

\n

with

"]
#1-TO_NEW_STRING
[0]
#1-STR_PRIMARY
["

There will be no issues this way.
